steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    args: ['storage', 'rm', '-a', '-r', '${_BUCKET}*']
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    args: ['storage', 'cp', '--recursive', 'build/*', '${_BUCKET}']
